### ISSUE TITLE
Sound in save states

### ISSUE THREAD

**Issue by XXXjoseXXX** [ShadauxCat/CATSFC#16]
If you disable the sound in a game, then create a save state and load to activate the sound is not heard

**Comment by amaro999** [comment]
If you choose to disable sound, create a save state, re-enable the sound and go back to the game it will freeze. You can still access the CATSFC menu, though. Doing so gives you the option to disable sound. If you choose it and go back to the game it will unfreeze. The conclusion is: Disabling sound and creating a save state are not compatible.

**Comment by Nebuleon** [comment]
Fixed in commit c01a2a42168695233ecc69c4a60ed918e7701fb9 (2012-12-28).

This was due to the SNES APU (Audio Processing Unit) getting disabled when the user muted sound, then its execution state was not saved in saved states at all. Now, muting the sound just causes the interface not to emit sound, but the APU keeps running and getting saved in saved states.

Saved states made before this commit with muted sound will keep being broken. New saved states will work if sound gets re-enabled.
