### ISSUE TITLE
Emulation good but slow, skipping

### ISSUE THREAD

**Issue by ReaperWolf** [ShadauxCat/CATSFC#21]
Testing rom for Demon's Crest (USA). Game runs, but gets very slow and choppy quickly.

**Comment by DaVince** [comment]
There are several different settings that can speed up emulation, like disabling sound or upping the CPU frequency. In a bug report, you should always list what you have already tried, because if you don't, the bug report gets really unclear, as yours shows. Is it slow under all circumstances? Even if you up the CPU frequency? How well does it run if you turn on/off sound?

**Comment by ReaperWolf** [comment]
I tried all different CPU frequency settings. I had not tried turning off the sound, however, I didn't realize it made much of a difference. Seems to run okay with sound off, as it turns out.

**Comment by ReaperWolf** [comment]
Played further with sound off, the game does still start getting a bit jerky after playing for a bit. Got to the boss of the second level this time before things got pretty well unplayable.

**Comment by DaVince** [comment]
I noticed there's this delay on the input that might actually be the rendering lagging behind. Games like Super Mario World become a lot more difficult to play because of it.

**Comment by ReaperWolf** [comment]
I kinda noticed that too but I wasn't sure if it was the emulation or just my DS buttons. Or hands.

The lag and choppiness that crops up after you play for a while goes away if you save state and reset, so I guess it's just the card running low on memory or something.

**Comment by DaVince** [comment]
I know what you mean, but the choppiness and delayed button reaction is already apparent when you just started the game, compared to NDSSFC. It might be a good idea to keep both on a cartridge so you can test them side-by-side.

The situation right now, I think, is that NDSSFC is a bit faster, but CATSFC is much more stable. I imagine it must be tough getting it to work well in the first place, though.

If not much has actually been changed about the emulation core to warrant the slightly worse performance, perhaps you could play with compiler optimizations, if you have any available?

**Comment by Nebuleon** [comment]
In commit d1fe64aef0298514150e543b1b13fbf03f33c3e1 (2012-12-23) (v 1.09) I have changed the emulation code to stop using global variables like OpAddress, Work8, Work16 and Work32. This creates much less work loading and storing global variables in memory **per** SNES CPU instruction.

**Comment by Nebuleon** [comment]
In CATSFC 1.16 (2013-01-08) I have improved the audio latency, which made automatic frameskipping much more playable. As this issue is not a strict subset of issue #27, I'll leave it open to get you guys' input on the latency.

**Comment by Nebuleon** [comment]
CATSFC 1.24, 1.27 and 1.28 improved audio latency even more, to the point where games did not primarily lag because of the audio anymore.

1.25 made the default value of Snes9x's Settings.SoundSync be FALSE for more fluid video.

1.27 reduced the time needed to draw frames in non-smoothed display modes from 2.8 milliseconds to 1.3, saving 3% CPU time.

1.28 reduced the time needed to get controls during a frame, saving about 2% more CPU time.

Right now, only chip games should have any noticeable slowdown.

**Comment by Nebuleon** [comment]
This bug will now be closed. Not all games can run on the DSTWO's relatively limited processor. It is a reality that we must deal with.
